# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onecorp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: luxswipe
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ls-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION_NAME} 
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE_NAME}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE_NAME}/index/*
  environment:
    TABLE_NAME: ${env:TABLE_NAME}

functions:
  api:
    handler: handler.main
    events:
      - httpApi: "*"